apiVersion: v1
data:
  ENVIRONMENT: Dev
  REGION: East US
  SOME_COMMON_ENVIRONMENT_VARIABLE: "false"
  acrHostname: pg.acr.io
  backendVersion: v1234
  deviceName: test123
  factoryID: "10"
  factoryName: Tabler Station
  historian.password: my-super-secret
  lower: ffr01
  uiEnabled: "true"
  upper: FFR01changed
kind: ConfigMap
metadata:
  name: platform-config
  namespace: dev-tabler-station-ffr01-busybox-busybox-uc2-perline
