apiVersion: federation.symphony/v1
kind: Catalog
metadata:
  name: busybox-tabler-station-ffr04-config-18155215650601212926
spec:  
  type: config
  properties:
    ENVIRONMENT: Dev
    REGION: Far Far Away
    SOME_COMMON_ENVIRONMENT_VARIABLE: "true"
    acrHostname: pg.acr.io
    deviceName: test123456789
    factoryID: "11"
    factoryName: Tabler Station
    historian.password: my-super-secret
    lower: ffr04
    replicas: "2"
    uc2-config.yaml: |
      backendVersion: v3456
      uiEnabled: "true"
    upper: FFR04
