apiVersion: v1
kind: Namespace
metadata:
  name: tabler-station-shared-busybox-busybox-uc1-shared 
  labels:
    environment: dev
    workspace: busybox-team
    workload: busybox
    deploymentTarget: busybox-busybox-uc1-shared
    someLabel: some-value
